-- Developer profiles + investigation runs (HB-26, Milestone 3.1).
--
-- Redirects the data model from "a requester's investigation" (the
-- requester-owned github_investigations table) to "a subject's profile". A
-- profile now belongs to the analyzed GitHub user and is keyed by their
-- normalized login so lookups by other people can reuse it.
--
-- Two profiles can coexist per login — one per `source`:
--   authored  = generated by the subject themselves (HB-29), may carry private
--               signal, visibility-controlled, default private.
--   observed  = generated by someone else's query (public data only), kept as a
--               reusable cache.
-- The composite unique key (github_login, source) is what guarantees the
-- "authored > observed" rule structurally: an observed regeneration can only
-- ever upsert the observed row, so it can never overwrite an authored one.
-- Picking authored over observed at read time is the reuse tree's job (HB-28).
--
-- investigation_runs is an append-only audit trail: one row per generation
-- (who triggered it, the workflow run id, status, timings). It is created up
-- front so the ephemeral Vercel Workflow run has a durable home to report into,
-- and points at the profile it produced once done.

-- developer_profiles ---------------------------------------------------------
create table if not exists public.developer_profiles (
	id uuid primary key default gen_random_uuid(),
	github_login text not null,                        -- normalized lowercase (dedupe / cache key)
	subject_user_id uuid references auth.users (id) on delete set null,
	source text not null check (source in ('authored', 'observed')),
	visibility text not null default 'private' check (visibility in ('private', 'public')),
	summary jsonb,                                     -- the single DeveloperSummary
	evidence_snapshot jsonb,                           -- structured tool outputs; filled by HB-27
	provenance jsonb,                                  -- identity block, tool calls, data-source counts, model
	generated_at timestamptz,
	fresh_until timestamptz,                           -- observed = generated_at + 7d; authored = null
	purge_after timestamptz,                           -- non-member observed hard-delete time (HB-28 cron)
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	unique (github_login, source)
);

comment on table public.developer_profiles is 'Subject-owned GitHub developer profiles, keyed by (github_login, source); service-role writes (HB-26).';

-- Fast path for "the member's own profiles" and account-deletion cleanup.
create index if not exists developer_profiles_subject_idx
	on public.developer_profiles (subject_user_id)
	where subject_user_id is not null;

-- Drives the scheduled purge of expired non-member observed profiles (HB-28).
create index if not exists developer_profiles_purge_idx
	on public.developer_profiles (purge_after)
	where purge_after is not null;

-- investigation_runs ---------------------------------------------------------
create table if not exists public.investigation_runs (
	id uuid primary key default gen_random_uuid(),
	profile_id uuid references public.developer_profiles (id) on delete set null,
	requested_by uuid not null references auth.users (id) on delete cascade,
	workflow_run_id text unique,
	target_login text not null,                        -- shown in "recent" list while running, before a profile exists
	status text not null default 'running' check (status in ('running', 'completed', 'failed')),
	started_at timestamptz not null default now(),
	completed_at timestamptz,
	error_message text
);

comment on table public.investigation_runs is 'Append-only audit trail of profile generations; per-requester history, service-role writes (HB-26).';

-- "My recent investigations" reads by requester, newest first.
create index if not exists investigation_runs_requested_by_idx
	on public.investigation_runs (requested_by, started_at desc);

-- Reverse lookup from a profile to the runs that produced it.
create index if not exists investigation_runs_profile_idx
	on public.investigation_runs (profile_id);

-- Row Level Security ---------------------------------------------------------
-- All writes go through the service role (workflow steps + API routes), which
-- bypasses RLS, so only select policies are defined.
alter table public.developer_profiles enable row level security;
alter table public.investigation_runs enable row level security;

-- observed profiles are readable by any authenticated user (cache reuse);
-- authored profiles are readable when public, else only by the subject.
drop policy if exists "Readable developer profiles" on public.developer_profiles;
create policy "Readable developer profiles" on public.developer_profiles for select
	using (
		auth.uid() is not null
		and (source = 'observed' or visibility = 'public' or subject_user_id = auth.uid())
	);

-- A member may read only the runs they triggered.
drop policy if exists "Users can read own runs" on public.investigation_runs;
create policy "Users can read own runs" on public.investigation_runs for select
	using (auth.uid() = requested_by);

-- Keep updated_at current on every write (reuses public.set_updated_at()).
drop trigger if exists developer_profiles_set_updated_at on public.developer_profiles;
create trigger developer_profiles_set_updated_at
before update on public.developer_profiles
for each row
execute function public.set_updated_at();
